name: reminder_app
description: "Set your reminder easily and never miss important tasks or events with Reminder App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.5+1
  
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  
  intl: ^0.20.2
  uuid: ^4.5.2
  path_provider: ^2.1.5
  
  sqflite: ^2.4.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/appIcon.png"

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
